### ISSUE TITLE
Electron Issue with ES6

### ISSUE THREAD

**Issue by murtazaali1999** [bradtraversy/electron-course-files#79]
Hi, Brad how's it going ? Hope your doing ok, Love your content btw

Ok, I'm working with Electron and tried to copy your image resizer project with latest ES6 and Electron versions. I'm in a pickle to be exact and cant find my way out of it. I've tried searching on the web on how to resolve this ES6 and electron war and tried to resolve it for days but couldn't find the right material. I don't want to switch to the older versions, Have been spending nights and check most of the main queries on GitHub. I request you to help me in this matter. Thanks in Advance 

![b2](https://user-images.githubusercontent.com/61330248/121786062-02c7fc80-cbd7-11eb-99ad-ea88fee51d5e.PNG)
![b1](https://user-images.githubusercontent.com/61330248/121786064-0491c000-cbd7-11eb-8797-97344788e230.PNG)

**Comment by murtazaali1999** [comment]
-Ive also tried inlining the renderer.js code.
-type:module
-changing from cjs to mjs
-changed require to import 
-also tried to use the npm esm module
didnt work

**Comment by wadeschofield** [comment]
I am having the same issue. There appears to be a change in the way that Node handles modules/imports.

**Comment by RodMachado** [comment]
For now, the solution for me was to downgrade the package versions:

```
    "imagemin": "^7.0.1",
    "imagemin-mozjpeg": "^9.0.0",
    "imagemin-pngquant": "^9.0.2",
    "slash": "^3.0.0"
```

These ☝️ will work.

**Comment by wadeschofield** [comment]
Thank you, that worked! I hope Electron gets all this sorted out. It would be nice to be able to use both import and require syntax.
